FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    gcc \
    build-essential \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip

RUN apt-get update; apt-get install -y ffmpeg
RUN python -m pip install --upgrade pip

WORKDIR /app

COPY requirements-ytdl.txt requirements.txt

RUN pip install -r requirements.txt
# RUN pip install -U https://github.com/coletdjnz/yt-dlp-youtube-oauth2/archive/refs/heads/master.zip


COPY utils/ utils/

COPY YoutubeDownloader/POD/YoutubeDownloaderPod.py YoutubeDownloaderPod.py
COPY YoutubeDownloader/POD/app.py app.py
COPY YoutubeDownloader/POD/startup.sh startup.sh

RUN ["chmod", "+x", "/app/startup.sh"]

CMD ["./startup.sh"]


